channels:
  - pytorch
  - defaults
dependencies:
  - pip:
    - absl-py==1.1.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - antlr4-python3-runtime==4.9.3
    - async-timeout==4.0.2
    - attrs==21.4.0
    - black==22.6.0
    - cachetools==5.2.0
    - charset-normalizer==2.1.0
    - click==8.1.3
    - cycler==0.11.0
    - dataclass-csv==1.4.0
    - dataclasses-json==0.5.7
    - datasets==2.3.2
    - dill==0.3.5.1
    - evaluate==0.1.2
    - filelock==3.7.1
    - fonttools==4.34.3
    - frozenlist==1.3.0
    - fsspec==2022.5.0
    - google-auth==2.9.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.47.0
    - huggingface-hub==0.8.1
    - hydra-core==1.2.0
    - idna==3.3
    - importlib-metadata==4.12.0
    - kiwisolver==1.4.3
    - markdown==3.3.7
    - marshmallow==3.17.0
    - marshmallow-enum==1.5.1
    - matplotlib==3.5.2
    - multidict==6.0.2
    - multiprocess==0.70.13
    - mypy-extensions==0.4.3
    - numpy==1.23.0
    - oauthlib==3.2.0
    - omegaconf==2.2.2
    - packaging==21.3
    - pandas==1.4.3
    - pathspec==0.9.0
    - pillow==9.2.0
    - platformdirs==2.5.2
    - protobuf==3.19.4
    - pyarrow==8.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydeprecate==0.3.2
    - pyhumps==3.7.2
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytorch-lightning==1.6.4
    - pytz==2022.1
    - pyyaml==6.0
    - regex==2022.6.2
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - responses==0.18.0
    - rsa==4.8
    - scipy==1.8.1
    - seaborn==0.11.2
    - six==1.16.0
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tokenizers==0.12.1
    - tomli==2.0.1
    - torch-tb-profiler==0.4.0
    - torchmetrics==0.9.2
    - tqdm==4.64.0
    - transformers==4.20.1
    - typing-extensions==4.3.0
    - typing-inspect==0.7.1
    - urllib3==1.26.9
    - werkzeug==2.1.2
    - xxhash==3.0.0
    - yarl==1.7.2
    - zipp==3.8.0
