pretrain_epochs: 2
train_epochs: 2
train_batch_size: 9
data_split_percent:
  - .01
  - .01
  - .01
  # - 1
  # - 1
  # - 1
eval_batch_size: 10
test_batch_size: 30
max_token_len: 700
num_dialogs: 
  - 1
  - 1
  - 1
  # - 127
  # - 20
  # - 34
overwrite:
  # - true
  # - true
  # - true
  - false 
  - false 
  - false 
should_test: false
num_turns: 26
train_domain_settings: ALL
is_multi_task: true
