project_root: /mounts/u-amo-d0/grad/adibm/projects/generative_tod/
data_root: processed_data/simple_tod
out_root: figures/model_size_calc
num_dialogs: 
  # - 1
  # - 1
  # - 1
  - 127
  - 20
  - 34
delexicalize: false
model_name: gpt2
domains:
  - Buses
  - Events
  - Flights
  - Homes
  - Hotels
  - Media
  - Movies
  - Music
  - RentalCars
  - Restaurants
  - RideSharing
  - Services
  - Travel
  - Weather
num_turns: 55