overwrite: 
  # - False
  # - False
  # - False
  - True
  - True
  - True
data_split_percent: 
  - 1
  - 1
  - 1
project_root: /mounts/u-amo-d0/grad/adibm/projects/generative_tod/
data_root: processed_data/simple_tod
out_root: figures/data_model_exploration
num_dialogs: 
  # - 1
  # - 1
  # - 1
  - 127
  - 20
  - 34
delexicalize: false
model_name: gpt2
domain_settings: seen
num_turns: 26
