data_split_percent:
  - 1
  - 1
  - 1
eval_batch_size: 6
test_batch_size: 133
max_token_len: 512
num_test_dialogs: 34
project_root: /project/msi290_uksr/generative_tod/
model: outputs/2022-07-30/22-00-06/results/train/checkpoint-7067/
num_turns: 26
overwrite:
  # - false
  # - false
  # - false
  - true
  - true
  - true
test_settings:
  - seen
