data_split_percent:
  - 1
  - 1
  - 0.1
eval_batch_size: 6
test_batch_size: 100
max_token_len: 512
num_test_dialogs: 34
# model: outputs/2022-07-27/20-07-27/results/train/checkpoint-14134
# model: outputs/2022-07-27/22-17-46/results/train/checkpoint-7067
# model: outputs/2022-07-28/17-06-27/results/train/checkpoint-1414
model: outputs/2022-07-29/19-46-27/results/train/checkpoint-14134
num_turns: 26
overwrite:
  - false
  - false
  - false
  # - true
  # - true
  # - true
test_settings:
  - seen