num_workers: 8
data_split_percent:
  - 1
  - 1
  - 1
eval_batch_size: 3
max_token_len: 1024
raw_data_root: data/dstc8-schema-guided-dialogue/
project_root: /mounts/u-amo-d0/grad/adibm/projects/generative_tod/
data_prep_out_root: processed_data/simple_tod
num_test_dialogs: 34
delexicalize: true
model: outputs/2022-07-12/13-18-03/results/checkpoint-8947
model_name: gpt2
device: cuda
generate_max_len: 1024