project_root: /mounts/u-amo-d0/grad/adibm/projects/generative_tod/
data_root: data/dstc8-schema-guided-dialogue/
out_root: processed_out/simple_tod
num_dialogs: None
seen_services: train/schema.json
# seen_services:
#   - Restaurants_1,
#   - Media_1